spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: shrikant
    url: jdbc:mysql://localhost:3306/smart_parking_system
    password: kale
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: smart-parking-system
server:
  port: '9191'